from __future__ import annotations

import csv
import io
import json

import httpx
import pytest


def test_normalize_certificate_and_parse_technical_regulations():
    from app.tqc_cnhq import normalize_certificate

    row = normalize_certificate(
        {
            "so_giay_chung_nhan": " C0955191224AE15A3 ",
            "ngay_cap_giay_chung_nhan": "2024-12-18T17:00:00.000Z",
            "don_vi_nop_ho_so_vn": "CÔNG TY INUT",
            "ten_san_pham_vn": "Thiết bị IoT",
            "ky_hieu": "T27G16",
            "ten_hang_san_xuat_vn": "TOMKO",
            "quy_chuan_ky_thuat": '["QCVN 54:2020/BTTTT"]',
            "tinh_trang_giay_chung_nhan": "còn hiệu lực",
        }
    )

    assert row["certificate_no"] == "C0955191224AE15A3"
    assert row["model"] == "T27G16"
    assert row["technical_regulations"] == ["QCVN 54:2020/BTTTT"]
    assert row["source_status"] == "còn hiệu lực"


def test_decode_official_qr_payload_round_trip():
    from app.tqc_cnhq import decode_qr_input

    # Generated by TQC's public frontend algorithm (CryptoJS AES + URL-safe base64).
    assert decode_qr_input("https://data-cnhq.tqc.gov.vn/?q=U2FsdGVkX1-8Q2k8Qf9xV8lR5m7fCq3p8J5wWw1z5Jg") is None
    assert decode_qr_input("C0955191224AE15A3") == "C0955191224AE15A3"


def test_client_calls_public_exact_endpoint_and_normalizes_response():
    from app.tqc_cnhq import TqcCnhqClient

    def handler(request: httpx.Request) -> httpx.Response:
        assert str(request.url) == "https://api-cnhq.tqc.gov.vn/api/search/C0955191224AE15A3"
        assert "x-api-key" not in request.headers
        return httpx.Response(
            200,
            json={
                "success": True,
                "data": {
                    "so_giay_chung_nhan": "C0955191224AE15A3",
                    "ky_hieu": "CPH2699",
                    "quy_chuan_ky_thuat": '["QCVN 117:2023/BTTTT"]',
                },
            },
        )

    client = TqcCnhqClient(transport=httpx.MockTransport(handler))
    try:
        result = client.lookup("C0955191224AE15A3")
    finally:
        client.close()
    assert result["certificate_no"] == "C0955191224AE15A3"
    assert result["model"] == "CPH2699"
    assert result["provenance"]["verification_status"] == "verified_live"


def test_client_maps_not_found_without_retry():
    from app.tqc_cnhq import TqcCnhqClient

    calls = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(request)
        return httpx.Response(200, json={"success": False, "error": "NOT_FOUND"})

    client = TqcCnhqClient(transport=httpx.MockTransport(handler))
    try:
        result = client.lookup("T27G16")
    finally:
        client.close()
    assert result is None
    assert len(calls) == 1


def test_index_search_is_accent_neutral_and_reports_local_scope(tmp_path, monkeypatch):
    monkeypatch.setenv("DATA_DIR", str(tmp_path))
    from app import db
    from app.tqc_cnhq import search_index, upsert_certificate

    db.reset_engine_for_tests()
    db.init_db()
    session = next(db.get_session())
    try:
        upsert_certificate(
            session,
            {
                "so_giay_chung_nhan": "C0955191224AE15A3",
                "don_vi_nop_ho_so_vn": "CÔNG TY CỔ PHẦN DI ĐỘNG THÔNG MINH",
                "ten_san_pham_vn": "Thiết bị đầu cuối",
                "ky_hieu": "CPH2699",
                "ten_hang_san_xuat_vn": "OPPO",
                "quy_chuan_ky_thuat": "[]",
                "tinh_trang_giay_chung_nhan": "còn hiệu lực",
            },
            verification_status="verified_cached",
        )
        result = search_index(session, q="di dong thong minh")
    finally:
        session.close()

    assert result["search_scope"] == "local_index"
    assert result["items"][0]["model"] == "CPH2699"


def test_csv_import_schema_is_bounded_and_deduplicated():
    from app.tqc_cnhq import parse_import_csv

    text = "certificate_no,qr_url\nC0955191224AE15A3,\nC0955191224AE15A3,\n"
    rows = parse_import_csv(text)
    assert rows == [{"certificate_no": "C0955191224AE15A3", "qr_input": ""}]


@pytest.fixture
def auth_client(tmp_path, monkeypatch):
    monkeypatch.setenv("DATA_DIR", str(tmp_path))
    monkeypatch.setenv("APP_ADMIN_PASSWORD", "NhapHang123@")
    from app.config import get_settings
    from app import db
    from app.auth import ensure_admin_seed
    from fastapi.testclient import TestClient
    from app.main import app

    get_settings.cache_clear()
    db.reset_engine_for_tests()
    db.init_db()
    session = next(db.get_session())
    ensure_admin_seed(session, get_settings())
    session.close()
    client = TestClient(app)
    assert client.post("/api/login", json={"username": "admin", "password": "NhapHang123@"}).status_code == 200
    return client


def test_tqc_search_and_exact_lookup_use_local_index(auth_client, monkeypatch):
    from app import standards_api
    from app import tqc_cnhq

    raw = {
        "so_giay_chung_nhan": "C0955191224AE15A3",
        "don_vi_nop_ho_so_vn": "CÔNG TY INUT",
        "ten_san_pham_vn": "Thiết bị IoT",
        "ky_hieu": "T27G16",
        "ten_hang_san_xuat_vn": "TOMKO",
        "quy_chuan_ky_thuat": "[]",
        "tinh_trang_giay_chung_nhan": "còn hiệu lực",
    }

    class FakeClient:
        def lookup(self, certificate_no):
            return tqc_cnhq.normalize_certificate(raw, source_url="https://api-cnhq.tqc.gov.vn/api/search/C0955191224AE15A3")

        def close(self):
            pass

    monkeypatch.setattr(standards_api.tqc_cnhq, "get_client", lambda _settings=None: FakeClient())
    response = auth_client.get("/api/standards/tqc/certificates/C0955191224AE15A3")
    assert response.status_code == 200
    assert response.json()["certificate"]["model"] == "T27G16"
    search = auth_client.get("/api/standards/tqc/search", params={"model": "t27g16"})
    assert search.status_code == 200
    assert search.json()["items"][0]["manufacturer"] == "TOMKO"


def test_tqc_import_requires_admin_and_returns_counts(auth_client, monkeypatch):
    from app import standards_api
    from app import tqc_cnhq

    class FakeClient:
        def lookup(self, certificate_no):
            return tqc_cnhq.normalize_certificate({
                "so_giay_chung_nhan": certificate_no,
                "ky_hieu": "CPH2699",
                "quy_chuan_ky_thuat": "[]",
            })

        def close(self):
            pass

    monkeypatch.setattr(standards_api.tqc_cnhq, "get_client", lambda _settings=None: FakeClient())
    response = auth_client.post("/api/standards/tqc/import", json={
        "entries": [{"certificate_no": "C0955191224AE15A3"}],
    })
    assert response.status_code == 200
    body = response.json()
    assert body["verified"] == 1
    assert body["items"][0]["status"] == "verified_live"
